### ISSUE TITLE
Scripts for image registration and regional analysis

### ISSUE THREAD

**Issue by xtang89** [richardxie1119/MEISTER#4]
Hello,

I was trying to reproduce the results but I cannot find the following scripts: 

- embed_3DCoronal.ipynb
- img_reg_updated.mat
- mri_reg_atlas.ipynb
- regional_analysis.py
- regmri_atlas_coronal.ipynb
- tissue_sc_mapping_deepmsi.ipynb

Could you provide the scripts or let me know where I can find them?
Thank you!

**Comment by richardxie1119** [comment]
> Hello,
> 
> I was trying to reproduce the results but I cannot find the following scripts:
> 
> * embed_3DCoronal.ipynb
> * img_reg_updated.mat
> * mri_reg_atlas.ipynb
> * regional_analysis.py
> * regmri_atlas_coronal.ipynb
> * tissue_sc_mapping_deepmsi.ipynb
> 
> Could you provide the scripts or let me know where I can find them? Thank you!

Hi, you should be able to find the scripts in the [multiscale_analysis repo](https://github.com/richardxie1119/multiscale_analysis). Closing the issue.
